server:
  address: localhost
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mirror
    username: mirror
    password: 111111
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456

logging:
  path: D:/work/log/${spring.application.name}
  level:
#    root: debug
    cn.com.mirror: debug
  file:
    max-size: 10MB
    max-history: 15

nas:
  location: d:/work/tmp

mirror:
  maxCliNum: 10
  maxEnable: true
