spring:
  profiles:
    active: dev
  application:
    name: mirrorweb-xyz

server:
  address: localhost
  port: 8080

logging:
  config: classpath:logback-config.xml
  controller:
    enabled: true



mapper:
  mappers:
    - cn.com.mirror.common.PgCommonMapper
  before: true
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
