server:
  port:8088

spring:
  redis:
    port: 6379
    password: mirror111
    host: 192.168.56.101

  datasource:
    url: jdbc:postgresql://192.168.56.101:5432/db_mirror
    username: mirror
    password: mirror111
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  path: /logs/


#project
mirror:
  project:
    name: testPrj
    path: D:/work/test/mirror/